export const latestActivitiesMockData = [
  {
    exercises: [
      {
        id: 6269563338227712,
        label: 'Daily routine',
        activity: {
          activityId: 1703,
          activityParentId: null,
          muscleMapping: {},
          category: 'DAILY_ROUTINE',
          difficulty: 'INBETWEEN',
          met: 4,
          bodyWeightRatio: null,
          rangeOfMotion: null,
          multiJoint: false,
          status: 'INACTIVE',
          name: {
            de: 'Tägliche Routine',
            fi: 'Päivittäinen rutiini',
            sv: 'Daglig träning',
            nb: 'Daglig rutine',
            en: 'Daily routine',
            fr: 'Routine quotidienne',
            es: 'Rutina diaria',
          },
          description: {
            de: 'Die tägliche Routine ist die Summe der Aktivitäten die du während eines Tages gemacht hast. Dazu gehören deine Schritte und deine Trainingseinheiten.\r\n\r\nDie Daten für die tägliche Routine kommen von verbundenen Geräten wie Fitness Trackern und Smartwatches.',
            fi: "Päivittäinen rutiini on päivän aikana suoritettavien toimintojen summa, mukaan lukien juokseminen, harjoittelu ja kävely.\n\nTiedot päivittäisestä rutiinistasi tulevat kytketyistä laitteista, kuten fitness-seuranta- ja älypuhelimista.'",
            sv: 'Daglig träning är summan av aktiviteter som utförs under dagen, inklusive löpning, träning och promenader.\r\n\r\nInformationen om din dagliga träning kommer från anslutna träningsappar och smartklockor.',
            nb: "Daglig rutine er summen av aktiviteter som gjøres i løpet av dagen, inkludert løping, trening og gåing.\n\nDataene om din daglige rutine kommer fra tilkoblede enheter som treningssporere og smartklokker.'",
            en: 'Daily routine are the sum of activities done during the day including running, workouts and walking.\r\n\r\nThe data about your daily routine comes from connected devices such as fitness trackers and smartwatches. ',
            fr: "'La routine quotidienne est la somme des activités réalisées au cours de la journée, comme la course à pied, l'entraînement et la marche.\r\n\r\n Les données relatives à votre routine quotidienne proviennent d'appareils connectés tels que les moniteurs d’activité et les montres intelligentes.'",
            es: "'La rutina diaria es la suma de las actividades realizadas durante el día, lo que incluye correr, hacer ejercicio y caminar. Los datos sobre tu rutina diaria provienen de dispositivos conectados como rastreadores de aptitud física y relojes inteligentes.'\r\n",
          },
          synonyms: {},
          images: ['https://storage.googleapis.com/activity-library-prod-prod-co/images/activities/NFPlMMqGSQzJ5mJj'],
          videos: [],
          previews: [],
          availableForMaxStrengthTests: false,
          recommendedForMuscleImbalance: false,
          strengthBenchmarkMale: null,
          strengthBenchmarkFemale: null,
          calculationMethod: null,
          maxStrengthTestBodyRegion: null,
          manuallyTracked: false,
          updatedAt: 1730887765000,
          equipments: [
            {
              id: null,
              type: 'NO_EQUIPMENT',
              images: [],
              names: {},
              createAt: null,
              updatedAt: null,
            },
          ],
          equipmentsV2: [
            {
              id: null,
              externalId: 'no-equipment',
              equipmentType: 'no-equipment',
              equipmentCategory: 'NO_EQUIPMENT',
              equipmentSubCategory: null,
              isEgymMachine: false,
              egymMachineType: null,
              creationTimestamp: null,
              updateTimestamp: null,
            },
          ],
          clientMetadata: {},
          basicMovements: [],
          categories: {
            category: 'ENDURANCE',
            child: {
              category: 'DAILY_ROUTINE',
              child: null,
            },
          },
          ownerId: null,
          laterality: null,
          weightGuidance: null,
        },
        sets: [
          {
            setType: 'TIME_BASED',
            numberOfReps: null,
            weight: null,
            duration: 0,
            distance: 733.7476765974425,
            heartRate: null,
            speed: null,
            incline: null,
            recoveryTime: null,
          },
        ],
        editable: false,
        deletable: false,
        completedAt: '2024-12-12T23:59:59',
        timezone: 'CET',
        sourceType: 'CONNECTED_APP',
        source: 'APPLE_HEALTH',
        origin: null,
        kiloCalories: 122,
        points: 20,
        hrmData: null,
        matrixSprint8: null,
        partnerData: null,
        summary: {
          totalDuration: 0,
          totalDistance: 733.7476765974425,
          verticalDistance: null,
          avgPace: null,
          avgHeartRate: null,
          maxHeartRate: null,
          avgSpeed: null,
          avgIncline: null,
        },
      },
    ],
    completedAt: '2024-12-12T23:59:59',
    timezone: 'CET',
    templateGroupId: null,
    workoutPlanName: null,
    workoutPlanImageUrl: null,
    workoutPlanGroupType: null,
  },
  {
    exercises: [
      {
        id: 6301158191398912,
        label: 'Daily routine',
        activity: {
          activityId: 1703,
          activityParentId: null,
          muscleMapping: {},
          category: 'DAILY_ROUTINE',
          difficulty: 'INBETWEEN',
          met: 4,
          bodyWeightRatio: null,
          rangeOfMotion: null,
          multiJoint: false,
          status: 'INACTIVE',
          name: {
            de: 'Tägliche Routine',
            fi: 'Päivittäinen rutiini',
            sv: 'Daglig träning',
            nb: 'Daglig rutine',
            en: 'Daily routine',
            fr: 'Routine quotidienne',
            es: 'Rutina diaria',
          },
          description: {
            de: 'Die tägliche Routine ist die Summe der Aktivitäten die du während eines Tages gemacht hast. Dazu gehören deine Schritte und deine Trainingseinheiten.\r\n\r\nDie Daten für die tägliche Routine kommen von verbundenen Geräten wie Fitness Trackern und Smartwatches.',
            fi: "Päivittäinen rutiini on päivän aikana suoritettavien toimintojen summa, mukaan lukien juokseminen, harjoittelu ja kävely.\n\nTiedot päivittäisestä rutiinistasi tulevat kytketyistä laitteista, kuten fitness-seuranta- ja älypuhelimista.'",
            sv: 'Daglig träning är summan av aktiviteter som utförs under dagen, inklusive löpning, träning och promenader.\r\n\r\nInformationen om din dagliga träning kommer från anslutna träningsappar och smartklockor.',
            nb: "Daglig rutine er summen av aktiviteter som gjøres i løpet av dagen, inkludert løping, trening og gåing.\n\nDataene om din daglige rutine kommer fra tilkoblede enheter som treningssporere og smartklokker.'",
            en: 'Daily routine are the sum of activities done during the day including running, workouts and walking.\r\n\r\nThe data about your daily routine comes from connected devices such as fitness trackers and smartwatches. ',
            fr: "'La routine quotidienne est la somme des activités réalisées au cours de la journée, comme la course à pied, l'entraînement et la marche.\r\n\r\n Les données relatives à votre routine quotidienne proviennent d'appareils connectés tels que les moniteurs d’activité et les montres intelligentes.'",
            es: "'La rutina diaria es la suma de las actividades realizadas durante el día, lo que incluye correr, hacer ejercicio y caminar. Los datos sobre tu rutina diaria provienen de dispositivos conectados como rastreadores de aptitud física y relojes inteligentes.'\r\n",
          },
          synonyms: {},
          images: ['https://storage.googleapis.com/activity-library-prod-prod-co/images/activities/NFPlMMqGSQzJ5mJj'],
          videos: [],
          previews: [],
          availableForMaxStrengthTests: false,
          recommendedForMuscleImbalance: false,
          strengthBenchmarkMale: null,
          strengthBenchmarkFemale: null,
          calculationMethod: null,
          maxStrengthTestBodyRegion: null,
          manuallyTracked: false,
          updatedAt: 1730887765000,
          equipments: [
            {
              id: null,
              type: 'NO_EQUIPMENT',
              images: [],
              names: {},
              createAt: null,
              updatedAt: null,
            },
          ],
          equipmentsV2: [
            {
              id: null,
              externalId: 'no-equipment',
              equipmentType: 'no-equipment',
              equipmentCategory: 'NO_EQUIPMENT',
              equipmentSubCategory: null,
              isEgymMachine: false,
              egymMachineType: null,
              creationTimestamp: null,
              updateTimestamp: null,
            },
          ],
          clientMetadata: {},
          basicMovements: [],
          categories: {
            category: 'ENDURANCE',
            child: {
              category: 'DAILY_ROUTINE',
              child: null,
            },
          },
          ownerId: null,
          laterality: null,
          weightGuidance: null,
        },
        sets: [
          {
            setType: 'TIME_BASED',
            numberOfReps: null,
            weight: null,
            duration: 0,
            distance: 3063.819009936174,
            heartRate: null,
            speed: null,
            incline: null,
            recoveryTime: null,
          },
        ],
        editable: false,
        deletable: false,
        completedAt: '2024-12-11T23:59:59',
        timezone: 'CET',
        sourceType: 'CONNECTED_APP',
        source: 'APPLE_HEALTH',
        origin: null,
        kiloCalories: 234,
        points: 38,
        hrmData: null,
        matrixSprint8: null,
        partnerData: null,
        summary: {
          totalDuration: 0,
          totalDistance: 3063.819009936174,
          verticalDistance: null,
          avgPace: null,
          avgHeartRate: null,
          maxHeartRate: null,
          avgSpeed: null,
          avgIncline: null,
        },
      },
    ],
    completedAt: '2024-12-11T23:59:59',
    timezone: 'CET',
    templateGroupId: null,
    workoutPlanName: null,
    workoutPlanImageUrl: null,
    workoutPlanGroupType: null,
  },
];
